#
# docker compose -f docker-compose.yml up -d
# docker compose -f docker-compose.yml down
#
# docker compose -f docker-compose.yml up -d minio
# docker compose -f docker-compose.yml down minio
#
# docker compose -f docker-compose.yml up -d mysqlserver
# docker compose -f docker-compose.yml down mysqlserver
#

#
version: '3.8'

#
include:
  - path: ./docker-minio.yml
  - path: ./docker-mysqlserver.yml

#
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/miniconda:1-3
    build:
      context: .
      dockerfile: Dockerfile.dev
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    volumes:
      - .:/workspace/bd-notebooks-module:cached
      - ${HOME}/.m2:/home/vscode/.m2
      - ${HOME}/.ivy2:/home/vscode/.ivy2
      - sandbox_apps_path:/apps
    depends_on:
      - minio
    extra_hosts:
      - docker.sandbox.net:172.18.0.1
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    #network_mode: service:mysqlserver
    network_mode: "sandbox.net"
    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

#
# Docker Volumes
#
volumes:
  #
  sandbox_apps_path:
    external: true
  #  
  sandbox_security_secrets:
    external: true
  #  
  sandbox_mysql_data:
    external: true
#
# Docker Networks
#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net
